"use client"
import "./globals.css";
import { Inter, Montserrat } from "next/font/google";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/Navbar";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-stone-900`}>
        <ThemeProvider enableSystem={true} attribute="class">
          <Navbar/>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
